import "@/styles/globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params:{locale} }) {
  return (
    <html lang={locale}>
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js" />
      </head>
      <body>
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  );
}
